from enum import Enum


class ClusterEventType(str, Enum):
    CREATING = "CREATING"
    DID_NOT_EXPAND_DISK = "DID_NOT_EXPAND_DISK"
    EXPANDED_DISK = "EXPANDED_DISK"
    FAILED_TO_EXPAND_DISK = "FAILED_TO_EXPAND_DISK"
    INIT_SCRIPTS_STARTING = "INIT_SCRIPTS_STARTING"
    INIT_SCRIPTS_FINISHED = "INIT_SCRIPTS_FINISHED"
    STARTING = "STARTING"
    RESTARTING = "RESTARTING"
    TERMINATING = "TERMINATING"
    EDITED = "EDITED"
    RUNNING = "RUNNING"
    RESIZING = "RESIZING"
    UPSIZE_COMPLETED = "UPSIZE_COMPLETED"
    NODES_LOST = "NODES_LOST"
    DRIVER_HEALTHY = "DRIVER_HEALTHY"
    DRIVER_UNAVAILABLE = "DRIVER_UNAVAILABLE"
    SPARK_EXCEPTION = "SPARK_EXCEPTION"
    DRIVER_NOT_RESPONDING = "DRIVER_NOT_RESPONDING"
    DBFS_DOWN = "DBFS_DOWN"
    METASTORE_DOWN = "METASTORE_DOWN"
    NODE_BLACKLISTED = "NODE_BLACKLISTED"
    PINNED = "PINNED"
    UNPINNED = "UNPINNED"

    def __str__(self) -> str:
        return str(self.value)
