name: Static analysis

on: [pull_request]

jobs:
  pre-commit-checks:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pre-commit and mkdocs
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit mkdocs

      - name: Run pre-commit
        run: |
          pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Run mkdocs build
        run: |
          mkdocs build --verbose --clean
